### ISSUE TITLE
GET requires preflight request when authenticated

### ISSUE THREAD

**Issue by bedeoverend** [SimplaElements/sm-utility-connect#4]
GET requests are sending an OPTIONS preflight request when authenticated, causing a significant lag on requests. While not an issues for majority of users (non-authenticated), still gives editors an impression of slow down.

Should be pretty simple fix just removing headers from GET `iron-ajax`

**Comment by KoryNunn** [comment]
This issue _may_ affect any user logged into simpla, viewing any site that uses simpla, in view mode.

**Comment by bedeoverend** [comment]
@KoryNunn authentication is currently per-domain so a user should only see this if they've logged in to Simpla on that particular site.
